-- drop для разработки
DROP TABLE IF EXISTS compilation_event CASCADE;
DROP TABLE IF EXISTS request CASCADE;
DROP TABLE IF EXISTS event CASCADE;
DROP TABLE IF EXISTS compilation CASCADE;
DROP TABLE IF EXISTS location CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS category CASCADE;
DROP TABLE IF EXISTS comment CASCADE;
DROP TABLE IF EXISTS subscriptions CASCADE;

--
CREATE TABLE IF NOT EXISTS category
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    VARCHAR(50) NOT NULL UNIQUE
);

CREATE INDEX IF NOT EXISTS idx_category_name ON category(name);


CREATE TABLE IF NOT EXISTS compilation
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pinned  BOOLEAN,
    title   VARCHAR(255)
);


CREATE TABLE IF NOT EXISTS users
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    VARCHAR(255) NOT NULL,
    email   VARCHAR(255) NOT NULL UNIQUE
    );

CREATE TABLE IF NOT EXISTS location
(
    id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lat NUMERIC(9,6) NOT NULL CHECK (lat BETWEEN -90 AND 90),
    lon NUMERIC(9,6) NOT NULL CHECK (lon BETWEEN -180 AND 180)
);

CREATE INDEX IF NOT EXISTS idx_location_lat on location(lat);
CREATE INDEX IF NOT EXISTS idx_location_lon on location(lon);
CREATE INDEX IF NOT EXISTS idx_location_coords on location(lat, lon);


CREATE TABLE IF NOT EXISTS event
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    annotation          VARCHAR(2000),
    category_id         BIGINT REFERENCES category(id) ON DELETE CASCADE,
    confirmed_requests  BIGINT,
    description         VARCHAR(7000),
    event_date          TIMESTAMP WITHOUT TIME ZONE,
    created_on          TIMESTAMP WITHOUT TIME ZONE,
    initiator_id        BIGINT REFERENCES users(id) ON DELETE CASCADE,
    location_id         BIGINT REFERENCES location(id) ON DELETE CASCADE,
    paid                BOOLEAN,
    participant_limit   BIGINT,
    published_on        TIMESTAMP WITHOUT TIME ZONE,
    request_moderation  BOOLEAN,
    state               VARCHAR(50),
    title               VARCHAR(120),
    -- расчетное поле из сервиса статистики, в бд не пересчитывается
    views               BIGINT
    );


CREATE TABLE IF NOT EXISTS request
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created     TIMESTAMP WITHOUT TIME ZONE,
    event       BIGINT REFERENCES event(id) ON DELETE CASCADE NOT NULL,
    requester   BIGINT REFERENCES users(id) ON DELETE CASCADE NOT NULL,
    status      varchar(25) NOT NULL
 );


CREATE TABLE IF NOT EXISTS compilation_event
(
    compilation_id BIGINT REFERENCES compilation (id) ON DELETE CASCADE NOT NULL,
    event_id       BIGINT REFERENCES event (id) ON DELETE CASCADE       NOT NULL,
    PRIMARY KEY (compilation_id, event_id)
);

CREATE TABLE IF NOT EXISTS comment
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text        VARCHAR(4000) NOT NULL,
    status      VARCHAR(50) NOT NULL,
    created     TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    event_id    BIGINT REFERENCES event(id) ON DELETE CASCADE NOT NULL,
    author_id   BIGINT REFERENCES users(id) ON DELETE CASCADE NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_comment_event_id_created ON comment(event_id, created DESC);
CREATE INDEX idx_comment_author_id_created ON comment(author_id, created DESC);
CREATE INDEX idx_comment_status_created ON comment(status, created DESC);

CREATE TABLE IF NOT EXISTS subscriptions
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT REFERENCES users (id) ON DELETE CASCADE NOT NULL,
    subscription_id BIGINT REFERENCES users (id) ON DELETE CASCADE NOT NULL,
    UNIQUE(user_id, subscription_id)
)